import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createApp } from '../backend/server.mjs';
import { orderStore } from '../backend/orders.mjs';

async function fixture() { const dir = await mkdtemp(join(tmpdir(), 'otaku-http-')); const orders = orderStore(dir); await orders.save({ id: 'cs_test_old', mode: 'test', status: 'ready_for_purchase', purchasingEnabled: false, fundingStatus: 'available', claimedBy: null, items: [{ catalogId: '10', name: 'Toji', quantity: 1 }] }); const server = createApp({ config: { agentToken: 'a'.repeat(32), origin: 'http://localhost', webhookSecret: 'x' }, orders, stripe: async () => ({}) }); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); return { dir, orders, server, base: `http://127.0.0.1:${server.address().port}`, token: 'a'.repeat(32) }; }
const post = (base, token, id, action, body) => fetch(`${base}/api/orders/${id}/${action}`, { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: JSON.stringify(body) });

test('concurrent claims have one winner, token protects every mutation, replay is idempotent, and old IDs are directly addressable', async () => { const f = await fixture(); try { const results = await Promise.all([post(f.base, f.token, 'cs_test_old', 'claim', { agentId: 'one' }), post(f.base, f.token, 'cs_test_old', 'claim', { agentId: 'two' })]); assert.equal(results.filter(r => r.status === 200).length, 1); const winner = results.find(r => r.status === 200); const claim = await winner.json(); const agentId = claim.order.claimedBy; const claimToken = claim.claimToken; assert.equal((await post(f.base, f.token, 'cs_test_old', 'purchase-plan', { agentId, claimToken: 'wrong' })).status, 401); assert.equal((await post(f.base, f.token, 'cs_test_old', 'purchase-plan', { agentId, claimToken })).status, 200); assert.equal((await post(f.base, f.token, 'cs_test_old', 'purchase-plan', { agentId, claimToken })).status, 200); assert.equal((await post(f.base, f.token, 'cs_test_old', 'tracking', { agentId, claimToken, carrier: 'UPS', trackingNumber: '1Z123' })).status, 409); assert.equal((await f.orders.get('cs_test_old')).status, 'purchase_prepared'); } finally { await new Promise(resolve => f.server.close(resolve)); await rm(f.dir, { recursive: true }); } });

test('held orders cannot be claimed and missing tokens fail closed', async () => { const f = await fixture(); try { await f.orders.save({ id: 'cs_test_held', mode: 'test', status: 'test_order_held', purchasingEnabled: false, fundingStatus: 'held', claimedBy: null, items: [] }); assert.equal((await post(f.base, f.token, 'cs_test_held', 'claim', { agentId: 'x' })).status, 409); assert.equal((await post(f.base, f.token, 'cs_test_old', 'purchase-plan', { agentId: 'x' })).status, 401); } finally { await new Promise(resolve => f.server.close(resolve)); await rm(f.dir, { recursive: true }); } });
